### Products Index
GET http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDg1NzA2NjJ9.rHpNdNk2yGEBodmMfIWyvRmAIjq3M6nYCsixRVfUw7Y



### Products Show
GET http://localhost:3000/products/19.json

### Products Create
POST http://localhost:3000/products
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDg1NzA2NjJ9.rHpNdNk2yGEBodmMfIWyvRmAIjq3M6nYCsixRVfUw7Y

{
  "input_name": "Test Run4",
  "input_price": 5.5,
  "input_description": "testing testing test",
  "input_image": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6_oT2eciScT-YsV3NZPzFWBycJ7OhEKLdQ80dhc7oJlmIUVrfgwUOyJc04WF_U8JSvd8&usqp=CAU", "httpherehere"],
  "input_in_stock": 5,
  "input_supplier_id": 2
}

### Products Update
PATCH http://localhost:3000/products/16
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDg1NzA2NjJ9.rHpNdNk2yGEBodmMfIWyvRmAIjq3M6nYCsixRVfUw7Y

{
  "input_name": "Demo Drill",
  "input_price": 65,
  "input_description": "Drill things, make a toy car?!",
  "input_image": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRonWq_m3sJarrIsimR15x3vkPq1j74uDR6OA&usqp=CAU", "hey hey here here"],
  "input_in_stock": 5,
  "input_supplier_id": 1
}

### Products Destroy
DELETE http://localhost:3000/products/21
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDg1NzA2NjJ9.rHpNdNk2yGEBodmMfIWyvRmAIjq3M6nYCsixRVfUw7Y

### Users create (signup)
POST http://localhost:3000/users
content-type: application/json

{
  "name": "Ororo Storm",
  "email": "ot@email.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "ll@gmail",
  "password": "password"
}

### Photos create
POST http://localhost:3000/photos.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDg1NzA2NjJ9.rHpNdNk2yGEBodmMfIWyvRmAIjq3M6nYCsixRVfUw7Y

{
  "name": "Test name",
  "width": 640,
  "height": 480
}

### Orders Create
POST http://localhost:3000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDg1NzA2NjJ9.rHpNdNk2yGEBodmMfIWyvRmAIjq3M6nYCsixRVfUw7Y

### Orders Show
GET http://localhost:3000/orders/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDg1NzA2NjJ9.rHpNdNk2yGEBodmMfIWyvRmAIjq3M6nYCsixRVfUw7Y

### Orders Index
GET http://localhost:3000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDg1NzA2NjJ9.rHpNdNk2yGEBodmMfIWyvRmAIjq3M6nYCsixRVfUw7Y


### carted_products Create
POST http://localhost:3000/carted_products
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDg1NzA2NjJ9.rHpNdNk2yGEBodmMfIWyvRmAIjq3M6nYCsixRVfUw7Y

{
  "input_quantity": 3,
  "input_status": "carted",
  "input_product_id": 10
}

### carted_products Index
GET http://localhost:3000/carted_products
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDg1NzA2NjJ9.rHpNdNk2yGEBodmMfIWyvRmAIjq3M6nYCsixRVfUw7Y

### carted_products Destroy
DELETE http://localhost:3000/carted_products/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDg1NzA2NjJ9.rHpNdNk2yGEBodmMfIWyvRmAIjq3M6nYCsixRVfUw7Y
